// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduProject.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20220625224249_Im")]
    partial class Im
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("EduProject.Models.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersKodu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("DersId");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("EduProject.Models.DersNotu", b =>
                {
                    b.Property<int>("DersNotuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersAdı")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konu")
                        .HasColumnType("TEXT");

                    b.HasKey("DersNotuId");

                    b.ToTable("DersNotu");
                });

            modelBuilder.Entity("EduProject.Models.Duyuru", b =>
                {
                    b.Property<int>("DuyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuyuruName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DuyuruTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("DuyuruText")
                        .HasColumnType("TEXT");

                    b.HasKey("DuyuruId");

                    b.ToTable("Duyuru");
                });

            modelBuilder.Entity("EduProject.Models.ForumBaslik", b =>
                {
                    b.Property<int>("ForumBaslikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ForumBaslikId");

                    b.ToTable("ForumBaslik");
                });

            modelBuilder.Entity("EduProject.Models.ForumComment", b =>
                {
                    b.Property<int>("ForumCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<int>("ForumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("ForumCommentId");

                    b.ToTable("ForumComment");
                });

            modelBuilder.Entity("EduProject.Models.Ilan", b =>
                {
                    b.Property<int>("IlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Arıyor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("atCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("iletisim")
                        .HasColumnType("TEXT");

                    b.HasKey("IlanId");

                    b.ToTable("Ilan");
                });

            modelBuilder.Entity("EduProject.Models.Sınav", b =>
                {
                    b.Property<int>("SınavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersAdı")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SınavId");

                    b.ToTable("Sınav");
                });

            modelBuilder.Entity("EduProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtSignUp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
